site_name: NoBullshit Academy
theme:
  feature:
    tabs: true
  favicon: 'assets/img/favicon.ico'
  name: 'material'
  language: 'ru'
  palette:
    primary: 'black'
    accent: 'indigo'
copyright: 'Copyright &copy; 2020 NoBullshit Academy'

nav:
  - Неделя 0:
    - Баш: Неделя 0/Баш.md
    - Гит: Неделя 0/Гит.md
    - Редактор: Неделя 0/Редактор.md
  - Что значит "сделать": done.md

extra:
  search:
    language: 'en, ru'

markdown_extensions:
  - codehilite